### PR TITLE
Example: count

### PR DESCRIPTION
**Pull request by tshemsedinov**

### CODE REVIEW

**Comment by tshemsedinov** [comment]
Here is you task @AvangardAA but please accept invutation

**Comment by AvangardAA** [comment]
My task is about counting sum of numeric values, shown JS example i can explain with block-schema

count

And idea i want to purpose: lets work with exceptions, you cant use +operator on different data types (integer + string, float + string and etc), so we will try to add our element to the total sum, and if we catch exception on that - just pass, because our element isn`t numeric.

**Review by AvangardAA — COMMENTED** [review]
```
def get_num_sum(container):
    summ = 0.0
    for i in container:
        try:
            summ += container[i]
        except Exception as e:
            pass

    return summ

print(get_num_sum({1: 2, 2: 'sieben', 3: 5, 4: 7}))
```

**Comment by tshemsedinov** [comment]
@AvangardAA please provide js version

**Pull request closed without merging**
