### PR TITLE
Example: replace

### PR DESCRIPTION
**Pull request by tshemsedinov**

### CODE REVIEW

**Comment by tshemsedinov** [comment]
It's your task @complectzero but see email for invitation to this organization

**Review by complectzero — COMMENTED** [review]
With all unnecessary blocks and lines removed:
```js
const replace = (str, subStr, replacer) => {
  const subStrIndex = str.indexOf(subStr);
  const startOfStr = str.substring(0, subStrIndex);
  const endOfStr = str.substring(subStrIndex + subStr.length, str.length);
  const res = startOfStr + replacer + endOfStr;
  return res;
};

const result = replace('Hello <username> and bye!', '<username>', 'Marcus');
console.log(result);
```

**Comment by complectzero** [comment]
Using js replace() method:
```js
const str = 'Hello <username> and bye!';

const result = str.replace('<username>', 'Marcus');
console.log(result);
```

**Comment by complectzero** [comment]
My try to implement it in python:
```py
def replace(string, substring, replacer):
    substring_index = string.index(substring)
    res = string[0:substring_index] + replacer + string[substring_index + len(substring):]
    return res
    
result = replace('Hello <username> and bye!', '<username>', 'Marcus')
print(result)
```

**Comment by tshemsedinov** [comment]
Handle edge cases, for example empty incoming string, or if there is zero occurrence of substring in initial string. See this edge cases in the code of task, there are not only crappy code, there are ideas.

**Comment by complectzero** [comment]
JS upgrade:
```js
const replace = (str, subStr, replacer) => {
  const subStrIndex = str.indexOf(subStr);
  if (str === '' || subStr === '' || subStrIndex === -1) {
    const errorMessage = 'Check, if everything is correct with your input data and try again, please.'
    return errorMessage;
  } else {
  const startOfStr = str.substring(0, subStrIndex);
  const endOfStr = str.substring(subStrIndex + subStr.length, str.length);
  const res = startOfStr + replacer + endOfStr;
  return res;
  };
};

const result = replace('Hello <username> and bye!', '<username>', 'Marcus');
console.log(result);
```

**Comment by complectzero** [comment]
Python update:

**Pull request closed without merging**
